### ISSUE TITLE
fresh NC 18 Installation 

### ISSUE THREAD

**Issue by trecords** [e-alfred/ocdownloader#151] opened 2020-01-30 10:05 UTC
### Steps to reproduce
1. Login NC
2. Go to OCDownloader
3. Click any links on sidebar such as "Active Downloads"

### Expected behaviour
Show desired page

### Actual behaviour
NC error occures

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache2

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** 18

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** NC website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
</summary>

  - accessibility: 1.4.0
  - activity: 2.11.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_external_gdrive: 0.4.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocdownloader: 1.7.5
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one (currently not supported by ocDownloader):** local/smb/sftp/...

**Are you using encryption (currently not supported by ocDownloader):** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

#### ocDownloader configuration:

**Which downloader are you using:** Aria2

**Do you use a proxy:** Yes

**Which protocols do you allow**: FTP/HTTP/Bittorrent/

##### Aria2c error log
<details>
<summary>Aria2c log file (set the log level to debug by using --log-level=debug)</summary>

```
Insert your Aria2c error log here
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
``` [index] Error: Exception: Argument 3 passed to OC\Files\Utils\Scanner::__construct() must implement interface OCP\EventDispatcher\IEventDispatcher, instance of OC\Log given, called in /var/www/nextcloud/apps/ocdownloader/controller/index.php on line 247 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\ocDownloader\Controller\Index {}, "Completes")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("IndexController", "Completes", OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Completes"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "ocdownloader.Index.Completes"})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Completes"})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/ocdownloader/completes")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.phpwnloader/completes
from 192.168.1.11 by turkel at 2020-01-30T09:58:56+00:00
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

<!-- Issue template modified from https://github.com/nextcloud/weather/blob/master/issue_template.md -->

**Comment by e-alfred** [comment] 2020-01-30 15:16
This is a duplicate of https://github.com/e-alfred/ocdownloader/issues/150. Please add your logs/comments to that bug report.

**Closed by e-alfred** 2020-01-30 15:16 UTC
Labels: duplicate
