### ISSUE TITLE
I can't open setting page

### ISSUE THREAD

**Issue by luvletter1205** [e-alfred/ocdownloader#110] opened 2019-01-31 07:21 UTC
i got this one in my log file
```
{  
   "reqId":"41jVJGI0MIJcBWVqGXB5",
   "level":3,
   "time":"2019-01-31T07:13:10+00:00",
   "remoteAddr":"***",
   "user":"***",
   "app":"index",
   "method":"GET",
   "url":"\/nextcloud\/index.php\/settings\/user",
   "message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function style()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(708): include()\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(497): OC_App::getForms('personal')\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(93): OC\\\\Settings\\\\Manager->getPersonalSections()\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(46): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#6 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/ocdownloader\\\/settings\\\/personal.php\",\"Line\":17}",
   "userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36",
   "version":"13.0.8.2"
}
```
Exception:
```
{  
   "Exception":"Error",
   "Message":"Call to undefined function style()",
   "Code":0,
   "Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/app.php(708): include()\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/Settings\/Manager.php(497): OC_App::getForms('personal')\n#2 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(93): OC\\Settings\\Manager->getPersonalSections()\n#3 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(46): OC\\Settings\\Controller\\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')\n#4 \/var\/www\/html\/nextcloud\/settings\/Controller\/CommonSettingsTrait.php(125): OC\\Settings\\Controller\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\n#5 \/var\/www\/html\/nextcloud\/settings\/Controller\/PersonalSettingsController.php(57): OC\\Settings\\Controller\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\n#6 [internal function]: OC\\Settings\\Controller\\PersonalSettingsController->index('personal-info')\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n#8 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Settings\\Controller\\PersonalSettingsController), 'index')\n#9 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Settings\\Controller\\PersonalSettingsController), 'index')\n#10 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OC\\\\Settings\\\\Con...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#12 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#13 \/var\/www\/html\/nextcloud\/lib\/base.php(999): OC\\Route\\Router->match('\/settings\/user')\n#14 \/var\/www\/html\/nextcloud\/index.php(42): OC::handleRequest()\n#15 {main}",
   "File":"\/var\/www\/html\/nextcloud\/apps\/ocdownloader\/settings\/personal.php",
   "Line":17
}
```
Trace
```
#0 /var/www/html/nextcloud/lib/private/legacy/app.php(708): include()
#1 /var/www/html/nextcloud/lib/private/Settings/Manager.php(497): OC_App::getForms('personal')
#2 /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php(93): OC\Settings\Manager->getPersonalSections()
#3 /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php(46): OC\Settings\Controller\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')
#4 /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php(125): OC\Settings\Controller\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')
#5 /var/www/html/nextcloud/settings/Controller/PersonalSettingsController.php(57): OC\Settings\Controller\PersonalSettingsController->getIndexResponse('personal', 'personal-info')
#6 [internal function]: OC\Settings\Controller\PersonalSettingsController->index('personal-info')
#7 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)
#8 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
#9 /var/www/html/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
#10 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#12 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#13 /var/www/html/nextcloud/lib/base.php(999): OC\Route\Router->match('/settings/user')
#14 /var/www/html/nextcloud/index.php(42): OC::handleRequest()
#15 {main}
```

**Comment by e-alfred** [comment] 2019-02-13 15:47
This is a duplicate of https://github.com/e-alfred/ocdownloader/issues/62, please add your issue there.

**Closed by e-alfred** 2019-02-13 15:47 UTC
