### ISSUE TITLE
I want youtube-dl download the bestvideo

### ISSUE THREAD

**Issue by MikuShare** [e-alfred/ocdownloader#51] opened 2017-11-06 14:28 UTC
I found that youtube-dl download the video is 720p, I want it to always download the best video, but do not know where to change it

**Comment by e-alfred** [comment] 2017-11-06 15:20
This is a duplicate of https://github.com/e-alfred/ocdownloader/issues/29. The problem is that with resolutions over 720p audio and video are provided separately and have to be combined afterwards.

**Closed** 2017-11-06 15:21 UTC
Labels: duplicate
