### ISSUE TITLE
Compatibility with NC v23

### ISSUE THREAD

**Issue by schniepp** [e-alfred/ocdownloader#235] opened 2021-12-22 13:57 UTC
This app is currently not compatible with NC v23.

**Comment by weeman1337** [comment] 2021-12-22 14:16
Thanks for the report. Sounds like a duplicate of #229 .

PR #230 is merged - waiting for the 1.8 release (ping @e-alfred )

Stand by ;)

**Closed by weeman1337** 2021-12-22 14:16 UTC

**Comment by schniepp** [comment] 2021-12-22 14:50
> Thanks for the report. Sounds like a duplicate of #229 .
Ooops. I guess #229 was already marked as "closed", but my NC 22 instance still reported the app to be incompatible with v23. That's why I must have only looked in the open issues, but not in the closed issues. Sorry about that. 

> PR #230 is merged - waiting for the 1.8 release (ping @e-alfred )
> 
> Stand by ;)
Wonderful, thank you!

**Comment by e-alfred** [comment] 2021-12-22 20:26
1.8.0 is now released. Sorry for the delay. Thanks to the work of @weeman1337!
