### ISSUE TITLE
Error:  Returned GID is null ! Is Aria2c running as a daemon ?

### ISSUE THREAD

**Issue by ArunJRK** [e-alfred/ocdownloader#45] opened 2017-09-30 11:05 UTC

**Comment by e-alfred** [comment] 2017-09-30 14:02
Did you follow the directions on how to set up Aria2 in the readme file? Without Aria2c running correctly ocDownloader won't work. Also, this is a duplicate of https://github.com/e-alfred/ocdownloader/issues/38.

**Closed by e-alfred** 2017-09-30 14:02 UTC
Labels: invalid

**Comment by tharga8616** [comment] 2018-02-21 11:03
Before you run this command:
`sudo -u www-data aria2c --enable-rpc --rpc-allow-origin-all -c -D --log=/var/log/aria2.log --check-certificate=false --save-session=/var/local/aria2c.sess --save-session-interval=2 --continue=true --input-file=/var/local/aria2c.sess --rpc-save-upload-metadata=true --force-save=true --log-level=warn`

make sure that the log owner is www-data

`chown www-data:www-data /var/log/aria2.log`

**Comment by p6002** [comment] 2020-11-18 18:33
any fix for that?
