### ISSUE TITLE
Weirdness in Dark theme

### ISSUE THREAD

**Issue by ghost** [e-alfred/ocdownloader#131] opened 2019-09-01 13:04 UTC
https://cloud.goalhost.net/index.php/s/9wCL23xpHQtzXQZ/preview

**Comment by e-alfred** [comment] 2019-10-14 09:49
Dark mode is not yet supported.

**Comment by e-alfred** [comment] 2020-04-22 08:25
Duplicate of https://github.com/e-alfred/ocdownloader/issues/163.

**Closed by e-alfred** 2020-04-22 08:25 UTC
Labels: enhancement
