### ISSUE TITLE
Add in youtube-dl menu pls other non youtube.com urls

### ISSUE THREAD

**Issue by PaddyPat** [e-alfred/ocdownloader#152] opened 2020-01-31 11:13 UTC
Please add in ocDownloader in Download via Youtube menu the option, to ignore "the real youtube-video-url could not be found"

"German: Die echte YouTube-Video-URL konnte nicht empfangen werden"

Why? youtube-dl can download from many other sources but in ocdownloader it can only download from youtube.com

thanks for your great work

**Comment by e-alfred** [comment] 2020-02-10 12:06
This request is a duplicate of https://github.com/e-alfred/ocdownloader/issues/89. There is a branch which addresses the problem, but it is far from finished at the moment: https://github.com/e-alfred/ocdownloader/tree/youtubedl-rework

**Closed by e-alfred** 2020-02-10 12:06 UTC
Labels: duplicate
