### ISSUE TITLE
Download directory -> External Storage, is this possible? 

### ISSUE THREAD

**Issue by kalak-sudo** [e-alfred/ocdownloader#159] opened 2020-03-29 11:55 UTC
Hi all!

I have tried saving the Download directory to be a FTP (external storage), and it says "SAVED", but after refreshing, it goes back to default configuration.

Am I doing something wrong?? 

Server: Debian 10 
ocDownloader:  1.7.5
Nextcloud: 17.0.1

Thanks in advanced!! :)

**Comment by e-alfred** [comment] 2020-03-29 15:30
This is a duplicate of https://github.com/e-alfred/ocdownloader/issues/30. External storage is currently not supported by ocDownloader and the external tools it uses (youtube-dl, Aria2). If you like to help fix this issue, any help is appreciated!

**Closed by e-alfred** 2020-03-29 15:30 UTC
Labels: duplicate
