### ISSUE TITLE
Creates new folder, instead recognize the existing folder.

### ISSUE THREAD

**Issue by beatrfrm** [e-alfred/ocdownloader#226] opened 2021-10-11 18:16 UTC
### Steps to reproduce
1.set the destination to: /common folder/movies (which is an existing folder)

### Expected behaviour
The destination for the movies or torrents will be the "movies" folder in the "common folder"

### Actual behaviour
It creates some new folders called: "common", "folder", "movies"
The path is the following: /common/folder/movies

The space won't be recognized by the software.

Thank you very much for your work!!

Operating system: Linux 3.16.85-52 #1 SMP PREEMPT Mon Jun 29 13:18:51 -03 2020 aarch64

Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)

Database: mysql 10.3.28

PHP version: 7.3.27-9+ubuntu18.04.1+deb.sury.org+1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 20.0.13 - 20.0.13.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - analytics: 3.6.1
 - announcementcenter: 4.0.2
 - apporder: 0.13.0
 - bookmarks: 10.0.0
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.4
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 4.0.3
 - contactsinteraction: 1.1.0
 - cookbook: 0.9.4
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.9
 - external: 3.7.3
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_bpm: 0.2.1
 - files_external: 1.11.1
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - fileslibreofficeedit: 1.0.2
 - geoblocker: 0.5.1
 - impersonate: 1.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - news: 16.1.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.1.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - ocdownloader: 1.7.12
 - password_policy: 1.10.1
 - passwords: 2021.10.10
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.10
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.14.2
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - welcome: 1.0.0
 - workflowengine: 2.2.1
Disabled:
 - admin_audit
 - circles
 - duplicatefinder
 - encryption
 - files_antivirus
 - firstrunwizard
 - maps
 - openhab
 - phonetrack
 - ransomware_protection
 - recommendations
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.13.1",
    "overwrite.cli.url": "http:\/\/net.hu\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "app_install_overwrite": [
        "cookbook",
        "uploaddetails"
    ],
    "updater.release.channel": "stable",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "allow_local_remote_servers": true,
    "activity_expire_days": 200,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "trashbin_retention_obligation": "auto, 5",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

+----------+----------------+---------+---------------------+--------------------------------------+---------------------------------------+------------------+-------------------+-------+
| Mount ID | Mount Point    | Storage | Authentication Type | Configuration                        | Options                               | Applicable Users | Applicable Groups | Type  |
+----------+----------------+---------+---------------------+--------------------------------------+---------------------------------------+------------------+-------------------+-------+
| 19       | /Local         | Local   | None                | datadir: "\/nfs\/server"             | readonly: false                       | beatr            |                   | Admin |
| 20       | /NAS Privát    | Local   | None                | datadir: "\/nfs\/server\/Eszter"     | readonly: false                       | Eszter           |                   | Admin |
| 21       | /NAS Közös     | Local   | None                | datadir: "\/nfs\/server\/Kozosmappa" | enable_sharing: true, readonly: false |                  

</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0

**Comment by weeman1337** [comment] 2021-12-05 11:23
Thanks for the report. This is a duplicate of #195.

**Closed by weeman1337** 2021-12-05 11:23 UTC
