### ISSUE TITLE
ocDownloader - Dark Mode

### ISSUE THREAD

**Issue by tobi614** [e-alfred/ocdownloader#177] opened 2020-09-08 16:35 UTC
### Steps to reproduce

Enable Dark Mode under settings -> accessibility. Go to Main App "ocDownloader".
### Expected behaviour

Background is black. Font is white.
### Actual behaviour

Faulty coloring. See picture.
![Error2](https://user-images.githubusercontent.com/64694684/92503809-138bb200-f202-11ea-85ed-fa2d203cba46.JPG)

### Versions

Nextcloud: 19.0.1
ocDownloader: 1.7.8

**Comment by e-alfred** [comment] 2020-09-08 18:44
Duplicate of https://github.com/e-alfred/ocdownloader/issues/163.

**Closed by e-alfred** 2020-09-08 18:44 UTC
